### ISSUE TITLE
Assertion Error when running prepare_data_inst.py

### ISSUE THREAD

**Issue by ouenal** [W1zheng/DKNet#3]
Hi,

I am getting an assertion error when running prepare_data_inst.py (`assert len(np.unique(check)) == len(check)`). This happens when processing scene0217.

I see that there is this specific if statement for scene 217 however it does not resolve the issue.
`if(fn == 'val/scene0217_00_vh_clean_2.ply' and instance_segids[0] == instance_segids[int(len(instance_segids) / 2)]):`
`    instance_segids = instance_segids[: int(len(instance_segids) / 2)]`
Can you provide a solution or give me some insight as to why scene 217 needs to be handled differently than others?

**Comment by W1zheng** [comment]
Hi,

I just use the general process following the previous methods. You can print 'fn' and check whether fn == 'val/scene0217_00_vh_clean_2.ply' when processing scene0217, and change the following string to the correct one like 'prefix/val/scene0217_00_vh_clean_2.ply'.

I hope the above solution may help you.
